export const locations = [
  {
    name: "Albany Park, Chicago, IL",
    slug: "albany-park-chicago-il",
    lat: 41.968,
    lng: -87.718,
  },
  {
    name: "Archer Heights, Chicago, IL",
    slug: "archer-heights-il",
    lat: 41.81,
    lng: -87.717,
  },
  {
    name: "Armour Square, Chicago, IL",
    slug: "armour-square-il",
    lat: 41.843,
    lng: -87.634,
  },
  { name: "Ashburn, Chicago, IL", slug: "ashburn-il", lat: 41.742, lng: -87.711 },
  {
    name: "Auburn Gresham, Chicago, IL",
    slug: "auburn-gresham-il",
    lat: 41.743,
    lng: -87.656,
  },
  { name: "Austin, Chicago, IL", slug: "austin-il", lat: 41.887, lng: -87.763 },
  {
    name: "Avalon Park, Chicago, IL",
    slug: "avalon-park-il",
    lat: 41.745,
    lng: -87.593,
  },
  {
    name: "Avondale, Chicago, IL",
    slug: "avondale-il",
    lat: 41.941,
    lng: -87.702,
  },
  {
    name: "Belmont Cragin, Chicago, IL",
    slug: "belmont-cragin-il",
    lat: 41.926,
    lng: -87.768,
  },
  { name: "Beverly, Chicago, IL", slug: "beverly-il", lat: 41.719, lng: -87.676 },
  {
    name: "Bridgeport, Chicago, IL",
    slug: "bridgeport-il",
    lat: 41.838,
    lng: -87.65,
  },
  {
    name: "Brighton Park, Chicago, IL",
    slug: "brighton-park-il",
    lat: 41.812,
    lng: -87.699,
  },
  {
    name: "Burnside, Chicago, IL",
    slug: "burnside-il",
    lat: 41.727,
    lng: -87.596,
  },
  {
    name: "Calumet Heights, Chicago, IL",
    slug: "calumet-heights-il",
    lat: 41.726,
    lng: -87.57,
  },
  { name: "Chatham, Chicago, IL", slug: "chatham", lat: 41.739, lng: -87.612 },
  {
    name: "Chicago Lawn, Chicago, IL",
    slug: "chicago-lawn-il",
    lat: 41.775,
    lng: -87.696,
  },
  {
    name: "Clearing, Chicago, IL",
    slug: "clearing-il",
    lat: 41.778,
    lng: -87.771,
  },
  { name: "Douglas, Chicago, IL", slug: "douglas-il", lat: 41.834, lng: -87.618 },
  { name: "Dunning, Chicago, IL", slug: "dunning-il", lat: 41.947, lng: -87.799 },
  {
    name: "East Garfield Park, Chicago, IL",
    slug: "east-garfield-park-il",
    lat: 41.881,
    lng: -87.702,
  },
  {
    name: "East Side, Chicago, IL",
    slug: "east-side-il",
    lat: 41.708,
    lng: -87.535,
  },
  {
    name: "Edgewater, Chicago, IL",
    slug: "edgewater-il",
    lat: 41.984,
    lng: -87.66,
  },
  {
    name: "Edison Park, Chicago, IL",
    slug: "edison-park-il",
    lat: 42.005,
    lng: -87.813,
  },
  {
    name: "Englewood, Chicago, IL",
    slug: "englewood-il",
    lat: 41.775,
    lng: -87.641,
  },
  {
    name: "Forest Glen, Chicago, IL",
    slug: "forest-glen-il",
    lat: 41.979,
    lng: -87.761,
  },
  {
    name: "Fuller Park, Chicago, IL",
    slug: "fuller-park-il",
    lat: 41.809,
    lng: -87.632,
  },
  {
    name: "Gage Park, Chicago, IL",
    slug: "gage-park-il",
    lat: 41.795,
    lng: -87.696,
  },
  {
    name: "Garfield Ridge, Chicago, IL",
    slug: "garfield-ridge-il",
    lat: 41.794,
    lng: -87.77,
  },
  {
    name: "Grand Boulevard, Chicago, IL",
    slug: "grand-boulevard-il",
    lat: 41.813,
    lng: -87.617,
  },
  {
    name: "Greater Grand Crossing, Chicago, IL",
    slug: "greater-grand-crossing-il",
    lat: 41.764,
    lng: -87.624,
  },
  {
    name: "Hegewisch, Chicago, IL",
    slug: "hegewisch-il",
    lat: 41.655,
    lng: -87.545,
  },
  { name: "Hermosa, Chicago, IL", slug: "hermosa-il", lat: 41.921, lng: -87.735 },
  {
    name: "Humboldt Park, Chicago, IL",
    slug: "humboldt-park-il",
    lat: 41.901,
    lng: -87.702,
  },
  {
    name: "Hyde Park, Chicago, IL",
    slug: "hyde-park-il",
    lat: 41.794,
    lng: -87.59,
  },
  {
    name: "Irving Park, Chicago, IL",
    slug: "irving-park-il",
    lat: 41.953,
    lng: -87.736,
  },
  {
    name: "Jefferson Park, Chicago, IL",
    slug: "jefferson-park-il",
    lat: 41.971,
    lng: -87.763,
  },
  { name: "Kenwood, Chicago, IL", slug: "kenwood-il", lat: 41.809, lng: -87.593 },
  {
    name: "Lakeview, Chicago, IL",
    slug: "lakeview-il",
    lat: 41.943,
    lng: -87.658,
  },
  {
    name: "Lincoln Park, Chicago, IL",
    slug: "lincoln-park-il",
    lat: 41.925,
    lng: -87.649,
  },
  {
    name: "Lincoln Square, Chicago, IL",
    slug: "lincoln-square-il",
    lat: 41.969,
    lng: -87.688,
  },
  {
    name: "Logan Square, Chicago, IL",
    slug: "logan-square-il",
    lat: 41.923,
    lng: -87.709,
  },
  { name: "Loop, Chicago, IL", slug: "loop-il", lat: 41.878, lng: -87.636 },
  {
    name: "Lower West Side, Chicago, IL",
    slug: "lower-west-side-il",
    lat: 41.855,
    lng: -87.665,
  },
  {
    name: "McKinley Park, Chicago, IL",
    slug: "mckinley-park-il",
    lat: 41.83,
    lng: -87.673,
  },
  {
    name: "Montclare, Chicago, IL",
    slug: "montclare-il",
    lat: 41.929,
    lng: -87.798,
  },
  {
    name: "Morgan Park, Chicago, IL",
    slug: "morgan-park-il",
    lat: 41.687,
    lng: -87.662,
  },
  {
    name: "Mount Greenwood, Chicago, IL",
    slug: "mount-greenwood-il",
    lat: 41.691,
    lng: -87.712,
  },
  {
    name: "Near North Side, Chicago, IL",
    slug: "near-north-side-il",
    lat: 41.892,
    lng: -87.63,
  },
  {
    name: "Near South Side, Chicago, IL",
    slug: "near-south-side-il",
    lat: 41.856,
    lng: -87.621,
  },
  {
    name: "Near West Side, Chicago, IL",
    slug: "near-west-side-il",
    lat: 41.878,
    lng: -87.664,
  },
  {
    name: "New City, Chicago, IL",
    slug: "new-city-il",
    lat: 41.808,
    lng: -87.656,
  },
  {
    name: "North Center, Chicago, IL",
    slug: "north-center-il",
    lat: 41.953,
    lng: -87.682,
  },
  {
    name: "North Lawndale, Chicago, IL",
    slug: "north-lawndale-il",
    lat: 41.858,
    lng: -87.717,
  },
  {
    name: "North Park, Chicago, IL",
    slug: "north-park-il",
    lat: 41.984,
    lng: -87.716,
  },
  {
    name: "Norwood Park, Chicago, IL",
    slug: "norwood-park-il",
    lat: 41.985,
    lng: -87.813,
  },
  { name: "O'Hare, Chicago, IL", slug: "ohare-il", lat: 41.978, lng: -87.904 },
  { name: "Oakland, Chicago, IL", slug: "oakland-il", lat: 41.822, lng: -87.602 },
  {
    name: "Washington Park, Chicago, IL",
    slug: "washington-park-il",
    lat: 41.793,
    lng: -87.617,
  },
  { name: "Pullman, Chicago, IL", slug: "pullman-il", lat: 41.693, lng: -87.606 },
  {
    name: "Riverdale, Chicago, IL",
    slug: "riverdale-il",
    lat: 41.661,
    lng: -87.603,
  },
  {
    name: "Lincoln Park, Chicago, IL",
    slug: "lincoln-park-il",
    lat: 41.921,
    lng: -87.651,
    cat: "north",
  },
  {
    name: "Lakeview, Chicago, IL",
    slug: "lakeview-il",
    lat: 41.943,
    lng: -87.658,
    cat: "north",
  },
  {
    name: "Wicker Park, Chicago, IL",
    slug: "wicker-park-il",
    lat: 41.908,
    lng: -87.676,
    cat: "north",
  },
  {
    name: "Bucktown, Chicago, IL",
    slug: "bucktown-il",
    lat: 41.922,
    lng: -87.68,
    cat: "north",
  },
  {
    name: "Logan Square, Chicago, IL",
    slug: "logan-square-il",
    lat: 41.923,
    lng: -87.709,
    cat: "north",
  },
  {
    name: "Old Town, Chicago, IL",
    slug: "old-town-il",
    lat: 41.907,
    lng: -87.637,
    cat: "north",
  },
  {
    name: "Uptown, Chicago, IL",
    slug: "uptown-il",
    lat: 41.966,
    lng: -87.656,
    cat: "north",
  },
  {
    name: "Ravenswood, Chicago, IL",
    slug: "ravenswood-il",
    lat: 41.968,
    lng: -87.674,
    cat: "north",
  },
  {
    name: "The Loop, Chicago, IL",
    slug: "the-loop-il",
    lat: 41.881,
    lng: -87.627,
    cat: "downtown",
  },
  {
    name: "River North, Chicago, IL",
    slug: "river-north-il",
    lat: 41.892,
    lng: -87.634,
    cat: "downtown",
  },
  {
    name: "Streeterville, Chicago, IL",
    slug: "streeterville",
    lat: 41.89588189481195, 
    lng: -87.63037495624414,
    cat: "downtown",
  },
  {
    name: "Gold Coast, Chicago, IL",
    slug: "gold-coast-il",
    lat: 41.906,
    lng: -87.628,
    cat: "downtown",
  },
  {
    name: "West Loop, Chicago, IL",
    slug: "west-loop-il",
    lat: 41.882,
    lng: -87.644,
    cat: "downtown",
  },
  {
    name: "South Loop, Chicago, IL",
    slug: "south-loop-il",
    lat: 41.856,
    lng: -87.627,
    cat: "downtown",
  },
  {
    name: "New Eastside, Chicago, IL",
    slug: "new-eastside-il",
    lat: 41.886,
    lng: -87.62,
    cat: "downtown",
  },
  {
    name: "Printer's Row, Chicago, IL",
    slug: "printers-row-il",
    lat: 41.875,
    lng: -87.631,
    cat: "downtown",
  },
];

export const HEADER_MENU = {
  apartment: {
    title: "apartment",
    menu: [
      {
        title: "Popular Searches",
        items: [
          {
            label: "All Apartments",
            link: "#",
          },
          {
            label: "Luxury Apartments",
            link: "#",
          },
          {
            label: "Loft Apartments",
            link: "#",
          },
          {
            label: "Short-Term Apartments",
            link: "#",
          },
          {
            label: "Best Apartments",
            link: "#",
          },
          {
            label: "Cheap Apartments",
            link: "#",
          },
          {
            label: "New Apartments",
            link: "#",
          },
        ],
      },
      {
        title: "Apartment Layout",
        items: [
          {
            label: "Studio Apartments",
            slug: "albany-park-chicago-il?beds=studio",
          },
          {
            label: "1 Bedroom Apartments",
            slug: "/albany-park-chicago-il?beds=1",
          },
          {
            label: "2 Bedroom Apartments",
            slug: "albany-park-chicago-il?beds=2",
          },
          {
            label: "3 Bedroom Apartments",
            slug: "albany-park-chicago-il?beds=3",
          },
          {
            label: "4+ Bedroom Apartments",
            slug: "albany-park-chicago-il?beds=4",
          },
        ],
      },
      {
        title: "Apartment Style",
        items: [
          {
            label: "Houses for Rent",
            link: "#",
          },
          {
            label: "Townhouses for Rent",
            link: "#",
          },
          {
            label: "Condos for Rent",
            link: "#",
          },
          {
            label: "Room for Rent",
            link: "#",
          },
        ],
      },
      {
        title: "Popular Amenities",
        items: [
          {
            label: "Furnished",
            link: "#",
          },
          {
            label: "In-Unit Laundry",
            link: "#",
          },
        ],
      },
    ],
  },
  neighborhoods: {
    title: "neighborhoods",
    menu: [
      {
        title: "Popular Downtown Neighborhoods",
        items: locations.filter((l) => l.cat === "downtown"),
      },
      {
        title: "Popular North Neighborhoods",
        items: locations.filter((l) => l.cat === "north"),
      },
    ],
  },
};

export const searchList =[
{
  name: "River North, Chicago, IL",
  slug: "river-north-il",
  lat: 41.892,
  lng: -87.634,
  cat: "downtown",
},
{
  name: "West Loop, Chicago, IL",
  slug: "west-loop-il",
  lat: 41.882,
  lng: -87.644,
  cat: "downtown",
},
{
  name: "Streeterville, Chicago, IL",
  slug: "streeterville",
  lat: 41.892,
  lng: -87.62,
  cat: "downtown",
},
{
  name: "Old Town, Chicago, IL",
  slug: "old-town-il",
  lat: 41.907,
  lng: -87.637,
  cat: "north",
},
{
  name: "Fulton market, Chicago, IL",
  slug: "fulton-market-chicago-il",
  lat: 41.8868,
  lng: 87.6522,
  cat: "north",
},
{
  name: "South Loop, Chicago, IL",
  slug: "south-loop-il",
  lat: 41.856,
  lng: -87.627,
  cat: "downtown",
},
{
  name: "lakeshore east, Chicago, IL",
  slug: "coast-at-lakeshore-east-chicago-il",
  lat: 41.8869,
  lng: -87.6181,
  cat: "downtown",
},

]